[package]
name = "rust_report"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tabled = "0.15"
once_cell = "1.19"
num-format = "0.4"
